# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

services:
  # --- Spring Boot App ---
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_rest
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    restart: unless-stopped

  # --- PostgresSQL ---
  postgres:
    image: postgres
    container_name: bank_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: